-- Create Database
CREATE DATABASE APlus;
GO

USE APlus;
GO

-- Create Tables
CREATE TABLE CUSTOMER(
    CustomerID char(5) NOT NULL PRIMARY KEY,
    FirstName varchar(20),
    LastName varchar(20),
    Gender varchar(5),
    DOB date,
    AccountID char(10) NOT NULL,
    ContactID char(10) NOT NULL,
    BankCardNo char(16) NOT NULL
);

CREATE TABLE LOCATION(
    LocationID char(6) NOT NULL PRIMARY KEY,
    ContactID char(10) NOT NULL,
    Street varchar(50),
    CityProvince varchar(50),
    DistrictTown varchar(50),
    CommuneWard varchar(50),
    ZipCode char(6)
);

CREATE TABLE WALLET_ACCOUNT(
    AccountID char(10) NOT NULL PRIMARY KEY,
    UserName varchar(15),
    BankCardNo char(16),
    WalletMoney money,
    SecurityID char(10) NOT NULL
);

CREATE TABLE CONTACT(
    ContactID char(10) NOT NULL PRIMARY KEY,
    Phone varchar(10),
    Mail varchar(30)
);

CREATE TABLE SECURITY(
    SecurityID char(10) NOT NULL PRIMARY KEY,
    FingerPrint varbinary(max),
    PinCode char(6),
    Password varchar(16)
);

CREATE TABLE TRANSACTIONS(
    TransID char(10) NOT NULL PRIMARY KEY,
    Volume int,
    OrderDate datetime,
    OrderStatus bit,
    PaymentID char(12),
    AccountID char(10) NOT NULL,
    OrderMessage varchar(100),
    CooperateID char(5) NOT NULL
);

CREATE TABLE TRANSBANK (
    TransID char(10) NOT NULL PRIMARY KEY,
    BankCardNo char(16),
    Volume int
);

CREATE TABLE TRANSWALLET (
    TransID char(10) NOT NULL PRIMARY KEY,
    AccountID char(10),
    Volume int
);

CREATE TABLE TRANS_LUCKY_WALLET (
    TransID char(10) NOT NULL PRIMARY KEY,
    AccountID char(10),
    Volume int
);

CREATE TABLE LUCKY_WALLET(
    AccountID char(10) NOT NULL PRIMARY KEY,
    LuckyWalletMoneyDetail money,
    InterestRate int
);

CREATE TABLE COMPANYPARTNER(
    CompanyID char(5) NOT NULL PRIMARY KEY,
    CompanyName varchar(30),
    Categories varchar(30),
    LocationID char(6) NOT NULL,
    CooperateID char(5) NOT NULL
);

CREATE TABLE COOPERATE(
    CooperateID char(5) NOT NULL PRIMARY KEY,
    CooperateType varchar(20),
    Commision decimal(5,1)
);

CREATE TABLE BANK(
    BankID char(10) NOT NULL PRIMARY KEY,
    BankName varchar(100),
    CooperateID char(5) NOT NULL,
    LocationID char(6) NOT NULL
);

CREATE TABLE BANK_ACCOUNT(
    BankCardNo char(16) NOT NULL PRIMARY KEY,
    BankID char(10) NOT NULL,
    BankMoneyDetail money
);

CREATE TABLE COMMISSION (
    TransID char(10) NOT NULL,
    CooperateID char(5) NOT NULL,
    TotalComission decimal(5,1),
    CONSTRAINT CK_COMMISSION PRIMARY KEY (TransID, CooperateID)
);

-- Add Foreign Key Constraints
ALTER TABLE COMMISSION
ADD CONSTRAINT FK1_COMMISSION FOREIGN KEY (TransID) REFERENCES TRANSACTIONS(TransID),
    CONSTRAINT FK2_COMMISSION FOREIGN KEY (CooperateID) REFERENCES COOPERATE(CooperateID);

ALTER TABLE CUSTOMER
ADD CONSTRAINT FK1_CUSTOMER FOREIGN KEY (AccountID) REFERENCES LUCKY_WALLET (AccountID),
    CONSTRAINT FK2_CUSTOMER FOREIGN KEY (ContactID) REFERENCES CONTACT (ContactID),
    CONSTRAINT FK5_CUSTOMER FOREIGN KEY (BankCardNo) REFERENCES BANK_ACCOUNT (BankCardNo);

ALTER TABLE LOCATION
ADD CONSTRAINT FK1_LOCATION FOREIGN KEY (ContactID) REFERENCES CONTACT (ContactID);

ALTER TABLE WALLET_ACCOUNT
ADD CONSTRAINT FK1_WALLET_ACCOUNT FOREIGN KEY (SecurityID) REFERENCES SECURITY (SecurityID);

ALTER TABLE TRANSACTIONS
ADD CONSTRAINT FK2_TRANSACTIONS FOREIGN KEY (AccountID) REFERENCES LUCKY_WALLET (AccountID),
    CONSTRAINT FK3_TRANSACTIONS FOREIGN KEY (CooperateID) REFERENCES COOPERATE (CooperateID),
    CONSTRAINT FK4_TRANSACTIONS FOREIGN KEY (AccountID) REFERENCES WALLET_ACCOUNT (AccountID);

ALTER TABLE COMPANYPARTNER
ADD CONSTRAINT FK1_COMPANYPARTNER FOREIGN KEY (LocationID) REFERENCES LOCATION (LocationID),
    CONSTRAINT FK2_COMPANYPARTNER FOREIGN KEY (CooperateID) REFERENCES COOPERATE (CooperateID);

ALTER TABLE BANK
ADD CONSTRAINT FK1_BANK FOREIGN KEY (CooperateID) REFERENCES COOPERATE (CooperateID),
    CONSTRAINT FK2_BANK FOREIGN KEY (LocationID) REFERENCES LOCATION(LocationID);

ALTER TABLE TRANSBANK
ADD CONSTRAINT FK2_TRANSBANK FOREIGN KEY (TransID) REFERENCES TRANSACTIONS (TransID),
    CONSTRAINT FK1_TRANSBANK FOREIGN KEY (BankCardNo) REFERENCES BANK_ACCOUNT (BankCardNo);

ALTER TABLE TRANSWALLET
ADD CONSTRAINT FK1_TRANSWALLET FOREIGN KEY (TransID) REFERENCES TRANSACTIONS (TransID),
    CONSTRAINT FK2_TRANSWALLET FOREIGN KEY (AccountID) REFERENCES WALLET_ACCOUNT(AccountID);

ALTER TABLE TRANS_LUCKY_WALLET
ADD CONSTRAINT FK1_TRANSLUCKYWALLET FOREIGN KEY (TransID) REFERENCES TRANSACTIONS (TransID),
    CONSTRAINT FK4_TRAN_LUCKY_WALLET FOREIGN KEY (AccountID) REFERENCES LUCKY_WALLET(AccountID);

ALTER TABLE LUCKY_WALLET
ADD CONSTRAINT FK1_LUCKY_WALLET FOREIGN KEY (AccountID) REFERENCES WALLET_ACCOUNT (AccountID);

ALTER TABLE WALLET_ACCOUNT
ADD CONSTRAINT FK1_WalletAccount FOREIGN KEY (BankCardNo) REFERENCES BANK_ACCOUNT (BankCardNo);

ALTER TABLE BANK_ACCOUNT
ADD CONSTRAINT FK1_BANK_ACCOUNT FOREIGN KEY (BankID) REFERENCES BANK(BankID);
